name: Robot Framework Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Download and extract ZIP
      run: |
        mkdir organo
        curl -L https://github.com/alura-cursos/robot-framework-organo/archive/refs/heads/main.zip -o organo.zip
        unzip organo.zip -d organo
        rm organo.zip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework

    - name: Start Projeto Organo
      run: |
        cd organo  
        npm install
        npm start

    - name: Run Robot Framework tests
      run: |
        robot -d Results ./features/

    - name: Publish Robot Framework HTML report
      if: always()  # Garante que este passo seja executado, mesmo se os passos anteriores falharem
      uses: actions/upload-artifact@v2
      with:
        name: robot-results
        path: Results
